# Typing Test Scoreboard Schema

type TypingScore @table {
  id: UUID! @default(expr: "uuidV4()")
  name: String!
  wpm: Int!
  accuracy: Int!
  date: Date!
  time: String!
  createdAt: Timestamp! @default(expr: "request.time")
}
